# Pre-commit configuration.
# https://pre-commit.com

# pre-commit install
# pre-commit run --all-files

default_stages:
  - pre-commit
  - pre-push
  - commit-msg
  - manual

repos:
  # Fix some errors with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix, --exit-zero ]
        name: "ruff: fixing"
      - id: ruff-format
        name: "ruff: formatting"

  # Lint Python files with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        name: "ruff: linting"
