$schema: https://json-schema.org/draft-07/schema
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed. Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
  session_secret_key:
    description: Secret key for session management
    format: password
    title: Session Secret Key
    type: string
    writeOnly: true
required:
- session_secret_key
title: Settings
type: object
